point_flags = [
    "stop",
    "crossroad",
    "dokan",
    "scrollY",
    "scrollA",
    "scroll",
    "focus",
    "camstop",
    "demo1",
    "demo2",
    "demo3",
    "demo4",
    "demo5",
    "demo6",
    "demo7",
    "sand",
    "ice",
    "noshift",
    "link1",
    "switch",
    "ura",
    "scale",
    "demostop",
    "tilt",
    "board",
    "link2",
    "link3",
    "link4",
    "link5",
    "anchor",
]
"""Available point flags in NSMBW."""

route_animations = [
    ("ジャンプ", "Jump"),
    ("道", "Walk Grass"),
    ("砂", "Walk Sand"),
    ("流砂", "Walk Quicksand"),
    ("雪", "Walk Snow"),
    ("氷", "Walk Ice"),
    ("木", "Walk Wood"),
    ("土", "Walk Dirt"),
    ("坂", "Snowy Slope"),
    ("氷坂", "Icy Slope"),
    ("はしご", "Metal Ladder"),
    ("はしご岩", "Rock Ladder"),
    ("はしご縄", "Rope Ladder"),
    ("はしご左", "Metal Ladder (Left)"),
    ("はしご右", "Metal Ladder (Right)"),
    ("ツタ", "Vine"),
    ("スイッチブロック", "(UNUSED) Switch Block"),
    ("雲", "(UNUSED) Walk Cloud"),
    ("水", "(UNUSED) Walk Water"),
]
"""Available route animations in NSMBW including unused animations."""
